- hosts: localhost
  tasks:
    - name: stateful_node
      spot.cloud_modules.azure_stateful_node:
        state: present   # absent = delete, present = create/update/import
        uniqueness_by: "id"
        vm_id: "vm-for-import-using-ansible"   # Provide this field to trigger import workflow
        do_not_update:
          - region
          - resource_group_name
        stateful_node_config:
          import_vm_config:                      # Import configuration
            draining_timeout: 120
            original_vm_name: "vm-for-import-using-ansible"
            resource_group_name: "AutomationResourceGroup"
            resource_retention_time: 2
        stateful_node:
          name: "ansible-stateful-node-example-with-action"
          description: "a sample Stateful Node created via Ansible"
          region: "eastus"
          resource_group_name: "AutomationResourceGroup"
          persistence:
            data_disks_persistence_mode: "reattach"
            os_disk_persistence_mode: "reattach"
            should_persist_data_disks: true
            should_persist_network: true
            should_persist_os_disk: true
          health:
            health_check_types: ["vmState"]
            auto_healing: true
            grace_period: 300
            unhealthy_duration: 120
          scheduling:
            tasks:
              - is_enabled: false
                cron_expression: "* * * 1 *"
                type: "pause"
              - is_enabled: true
                cron_expression: "* * * 2 *"
                type: "resume"
          strategy:
            draining_timeout: 300
            fallback_to_od: true
            preferred_lifecycle: "spot"
            revert_to_spot:
              perform_at: "always"
            signals:
              - timeout: 180
                type: "vmReady"
              - timeout: 210
                type: "vmReadyToShutdown"
          compute:
            zones: ["1", "2"]
            preferred_zone: "2"
            vm_sizes:
              od_sizes: ["standard_a1_v2", "standard_a2_v2"]
              spot_sizes: ["standard_a1_v2", "standard_a2_v2"]
              preferred_spot_sizes: ["standard_a1_v2"]
            launch_specification:
              boot_diagnostics:
                is_enabled: true
                type: "managed"
              tags:
                - tag_key: "Creator"
                  tag_value: "Ansible Test"
                - tag_key: "Name"
                  tag_value: "Ansible Detailed Example For Import"
      register: result
    - debug: var=result
