#In this basic example, we create a simple elastigroup

- hosts: localhost
  tasks:
    - name: create elastigroup
      spot.cloud_modules.aws_elastigroup:
          name: ansible_test_group
          state: present
          risk: 100
          availability_vs_cost: balanced
          availability_zones:
            - name: us-east-2c
              subnet_id: subnet-123c
          image_id: test-ami
          key_pair: test-key-pair
          max_size: 2
          min_size: 0
          target: 0
          unit: instance
          monitoring: False
          on_demand_instance_type: m4.large
          product: Linux/UNIX
          tags:
            - Name: ansible_test_group
          security_group_ids:
            - sg-default
          spot_instance_types:
            - m4.xlarge
            - m5.xlarge
          do_not_update:
            - image_id
            - target
            - user_data
      register: result
    - debug: var=result