# In this basic example, we create a simple elastigroup wit beanstalk integration

- hosts: localhost
  tasks:
    - name: create elastigroup
      spot.cloud_modules.aws_elastigroup:
        account_id:
        token:
        name: ansible_test_beanstalk_group
        state: present
        risk: 100
        availability_vs_cost: balanced
        availability_zones:
          - name: us-west-2b
            subnet_id: subnet-1ba25052
        image_id: ami-f173cc91
        key_pair: Noam-key
        max_size: 2
        min_size: 0
        target: 0
        unit: instance
        monitoring: false
        on_demand_instance_type: m4.large
        product: Linux/UNIX
        elastic_beanstalk:
          environment_id: e-3tkmbj7hzc
          managed_actions:
            platform_update:
              perform_at: timeWindow
              time_window: Sun:01:00-Sun:02:00
              update_level: minorAndPatch
        security_group_ids:
          - sg-default
        spot_instance_types:
          - m4.xlarge
          - m5.xlarge
        do_not_update:
          - image_id
          - target
          - user_data
      register: result
    - debug: var=result
