#Integrate and Spotinst elastigroup with Stateful delete options

- hosts: localhost
  tasks:
    - name: create elastigroup
      spot.cloud_modules.aws_elastigroup:
          account_id: 
          token: 
          name: ansible_stateful_group
          state: absent
          risk: 100
          availability_vs_cost: balanced
          availability_zones:
            - name: us-west-2b
              subnet_id: subnet-1ba25052
          image_id: ami-f173cc91
          key_pair: Noam-key
          max_size: 2
          min_size: 0
          target: 0
          unit: instance
          monitoring: False
          on_demand_instance_type: m4.large
          product: Linux/UNIX
          tags:
            - Name: ansible_test_group
            - Environment: dev
          security_group_ids:
            - sg-default
          spot_instance_types:
            - m4.xlarge
            - m5.xlarge
          do_not_update:
            - image_id
            - target
            - user_data
          stateful_deallocation_should_delete_images: false
          stateful_deallocation_should_delete_network_interfaces: false
          stateful_deallocation_should_delete_snapshots: false
          stateful_deallocation_should_delete_volumes: false
      register: result
    - debug: var=result