# Integrate and Spotinst elastigroup with AWS's CodeDeploy
- hosts: localhost
  tasks:
    - name: create elastigroup
      spot.cloud_modules.aws_elastigroup:
        account_id:
        token:
        name: ansible_code_deploy_group
        state: absent
        risk: 100
        availability_vs_cost: balanced
        availability_zones:
          - name: us-west-2b
            subnet_id: subnet-1ba25052
        image_id: ami-f173cc91
        key_pair: Noam-key
        max_size: 2
        min_size: 0
        target: 0
        unit: instance
        monitoring: false
        on_demand_instance_type: m4.large
        product: Linux/UNIX
        code_deploy:
          deployment_groups:
            - application_name: test-app-1
              deployment_group_name: test-deployment-1
            - application_name: test-app-1
              deployment_group_name: test-deployment-2
          clean_up_on_failure: false
          terminate_instance_on_failure: true
        tags:
          - Name: ansible_test_group
          - Environment: dev
        security_group_ids:
          - sg-default
        spot_instance_types:
          - m4.xlarge
          - m5.xlarge
        do_not_update:
          - image_id
          - target
          - user_data
      register: result
    - debug: var=result
