# Persist your mounted root & data volumes along with connected ip addresses

- hosts: localhost
  tasks:
    - name: create elastigroup
      spot.cloud_modules.aws_elastigroup:
        name: ansible_test_group
        state: present
        risk: 100
        availability_vs_cost: balanced
        availability_zones:
          - name: us-east-2c
            subnet_id: subnet-123c
          - name: us-east-2b
            subnet_id: subnet-123b
          - name: us-east-2a
            subnet_id: subnet-123a
        image_id: test-ami
        key_pair: test-key-pair
        max_size: 2
        min_size: 0
        target: 0
        unit: instance
        monitoring: false
        on_demand_instance_type: m4.large
        product: Linux/UNIX
        user_data: IyEvdXNyL2Jpbi9lbnYgYmFzaA==
        shutdown_script: IyEvdXNyL2Jpbi9lbnYgYmFzaA==
        persistence:
          should_persist_root_device: false
          should_persist_block_devices: true
          should_persist_private_ip: false
          block_devices_mode: reattach
        private_ips:
          - 1.2.3.4
          - 2.3.4.5
        tags:
          - Name: ansible_test_group
          - Environment: dev
        security_group_ids:
          - sg-default
        spot_instance_types:
          - m4.xlarge
          - m5.xlarge
        do_not_update:
          - image_id
          - target
          - user_data
      register: result
    - debug: var=result
